Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "minikube" do |kube|
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "4"
  end

  config.vm.network "forwarded_port",
      guest: 8001,
      host:  8001,
      auto_correct: true
	  
  config.vm.network "forwarded_port",
      guest: 8443,
      host:  8443,
      auto_correct: true
	  
  config.vm.network "forwarded_port",
      guest: 3306,
      host:  3306,
      auto_correct: true
	  
  config.vm.network "forwarded_port",
      guest: 9000,
      host:  9000,
      auto_correct: true
    	  
  args = []
  config.vm.provision "shell",
	  path: "scripts/kubectl.sh",
      args: args

  args = []
  config.vm.provision "shell",
	  path: "scripts/docker.sh",
      args: args
	  
  args = []
  config.vm.provision "shell",
	  path: "scripts/minikube.sh",
      args: args

  args = []
  config.vm.provision "shell",
	  path: "scripts/kubernetes.sh",
      args: args

  end

end
